name: SmartInvs
version: 1.2.8
description: Inventory API for your Bukkit Plugins.
author: MinusKube
website: https://github.com/MinusKube/SmartInvs
main: cymru.asheiou.inv.SmartInvsPlugin
api-version: '1.21'